import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import { Suspense } from "react";
import LoadingPage from "./loading";
import { FaHeart } from "react-icons/fa";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen bg-slate-900">
        <NavBar />
        <Suspense fallback={<LoadingPage />}>
          {children}
          <footer className="flex h-12 w-full flex-row items-center justify-center gap-x-10 bg-slate-800">
            <span>2023</span>
            <span className="flex">
              Created By{" "}
              <FaHeart className="ml-1 mt-0.5 text-xl text-red-500" />
            </span>
            <Link className="active:text-yellow-500" href="/privacy">
              <span>Privacy</span>
            </Link>
          </footer>
        </Suspense>
      </body>
    </html>
  );
}
